import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner = `/*
Yazi Explorer for Obsidian — https://github.com/vi000246/obsidian-yazi
THIS IS A GENERATED/BUNDLED FILE. Read the source in src/ instead.
*/
`;

const prod = process.argv[2] === "production";

/*
 * 開發時直接把產物寫進 vault 的 plugin 資料夾，省掉「build 完再複製」那一步。
 * 路徑放在 .env.local（不進 git），格式：
 *     VAULT_PLUGIN_DIR=C:\\Users\\xxx\\vault\\.obsidian\\plugins\\yazi-explorer
 * 沒設定就只產在 repo 根目錄。
 */
const readEnvLocal = () => {
  try {
    const raw = fs.readFileSync(".env.local", "utf8");
    const m = /^VAULT_PLUGIN_DIR\s*=\s*(.+)$/m.exec(raw);
    return m ? m[1].trim().replace(/^["']|["']$/g, "") : null;
  } catch (e) {
    return null;
  }
};

const outDirs = ["."];
const vaultDir = prod ? null : readEnvLocal();
if (vaultDir) outDirs.push(vaultDir);

/* styles.css 與 manifest.json 不經過 bundler，但開發時要跟著複製過去，
   不然改了 CSS 卻要自己記得複製 —— 那種「明明改了卻沒效果」最浪費時間。 */
const copyAssets = () => {
  for (const dir of outDirs.slice(1)) {
    for (const f of ["styles.css", "manifest.json"]) {
      try {
        fs.copyFileSync(f, path.join(dir, f));
      } catch (e) {
        console.warn("複製 " + f + " 到 " + dir + " 失敗：" + e.message);
      }
    }
  }
};

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.js"],
  bundle: true,
  // Obsidian 自己提供這些，打包進去會壞掉（obsidian）或根本不存在（electron/node builtins）
  external: ["obsidian", "electron", "@codemirror/*", "@lezer/*", ...builtins],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: false, // 刻意不壓：審查者要看得懂產物，使用者回報問題時行號才有意義
});

if (prod) {
  await context.rebuild();
  await context.dispose();
} else {
  copyAssets();
  await context.watch();
  if (vaultDir) {
    // esbuild 的 outfile 只能有一個，所以 watch 模式自己再複製一份到 vault
    fs.watchFile("main.js", { interval: 300 }, () => {
      for (const dir of outDirs.slice(1)) {
        try {
          fs.copyFileSync("main.js", path.join(dir, "main.js"));
        } catch (e) {
          console.warn("複製 main.js 失敗：" + e.message);
        }
      }
      copyAssets();
      console.log("→ 已同步到 " + vaultDir);
    });
    console.log("watch 中，產物會同步到 " + vaultDir);
  }
}
